newrelic/nri-nginx

- Makefile-package.mk
Fix package dep version number
Add a detailed description and purpose of your changes.
Link the issue it solves (if there is one).
> Fix package dep version number

- CHANGELOG.md
- Makefile
Versioning numbers and patch notes are incorrect.
Updated golint dependency.
> Update changelog versions

- CHANGELOG.md
- src/inventory.go
This PR will fix the issue with nginx integration that could generate high CPU load if the config_path parameter provided in the configuration was a directory instead of a file. This is done by improving the error handling when the nginx config file is read in order to create the inventory.
https://newrelic.atlassian.net/browse/IHOST-1699
> IHOST-1699: Fixed high cpu usage

- CHANGELOG.md
Release v1.0.2
https://newrelic.atlassian.net/browse/IHOST-1695
> IHOST-1695: Release v1.0.2

- src/nginx.go
update version
Update version on nginx
> Update version on nginx

- nginx-config.yml.sample
- src/nginx.go
- src/nginx_test.go
changed entity type and provide backwards compatibility
> Changed entity type and provide backwards compatibility

- src/nginx.go
Added backwards compatibility for decoration with local entity.
> IHOST-1227 add port metric set attribute in local entity

- nginx-definition.yml
Add a detailed description and purpose of your changes.
Link the issue it solves (if there is one).
> Update to protocol v3

- CHANGELOG.md
- tests/integration/json-schema-files/nginx-schema-inventory.json
- tests/integration/json-schema-files/nginx-schema-metrics.json
- tests/integration/json-schema-files/nginx-schema.json
- vendor/github.com/newrelic/infra-integrations-sdk/data/metric/metrics.go
- vendor/github.com/newrelic/infra-integrations-sdk/integration/entity.go
- vendor/github.com/newrelic/infra-integrations-sdk/integration/entity_id.go
- vendor/github.com/newrelic/infra-integrations-sdk/integration/integration.go
- vendor/vendor.json
Upgrade To SDK v3.1.5 
- [x ] add a risk label after carefully considering the "blast radius" of your changes
- [x ] describe the _intent_ of your changes in the description. don't just rewrite your code in prose
- [x ] assign at least one reviewer
> [Ihost 2175] Upgrade To SDK v3.1.5

- CHANGELOG.md
- src/metrics.go
- src/nginx.go
Default: `true`. Set it to `false` if you have self-signed certificates
and want to avoid the integration to fail.
> Added validate_certs configuration option

- CHANGELOG.md
- src/nginx.go
Fixed integration version reporting, which was not correct in agent 1.5.0
> Updated integration version

- nginx-config.yml.k8s_sample
Adding configuration sample for running on Kubernetes.
> Adding Config sample for Kubernetes

- CHANGELOG.md
- nginx-config.yml.sample
- src/nginx.go
- Include the status_url in the inventory configuration since this is required for the entity name.
Add a detailed description and purpose of your changes.
Link the issue it solves (if there is one).
> Updated the config sample

- nginx-config.yml.sample
Adding the option for Validate Certs that is in the arguments so customers can use it
Add a detailed description and purpose of your changes.
Link the issue it solves (if there is one).
> Update nginx-config.yml.sample with Validate_Certs

- vendor/github.com/newrelic/infra-integrations-sdk/LICENSE
- vendor/github.com/newrelic/infra-integrations-sdk/args/args.go
- vendor/github.com/newrelic/infra-integrations-sdk/args/json.go
- vendor/github.com/newrelic/infra-integrations-sdk/data/attribute/attribute.go
- vendor/github.com/newrelic/infra-integrations-sdk/data/event/event.go
- vendor/github.com/newrelic/infra-integrations-sdk/data/inventory/inventory.go
- vendor/github.com/newrelic/infra-integrations-sdk/data/metric/metrics.go
- vendor/github.com/newrelic/infra-integrations-sdk/data/metric/set_marshal.go
- vendor/github.com/newrelic/infra-integrations-sdk/data/metric/source_type.go
- vendor/github.com/newrelic/infra-integrations-sdk/integration/entity.go
- vendor/github.com/newrelic/infra-integrations-sdk/integration/entity_id.go
- vendor/github.com/newrelic/infra-integrations-sdk/integration/integration.go
- vendor/github.com/newrelic/infra-integrations-sdk/integration/options.go
- vendor/github.com/newrelic/infra-integrations-sdk/log/log.go
- vendor/github.com/newrelic/infra-integrations-sdk/persist/storer.go
- vendor/vendor.json
Restore infra sdk dependencies to vendor folder
> fix(deps): add missing vendor dependencies

- nginx-config.yml.k8s_sample
- nginx-config.yml.sample
> fix(docs): remove reference from endpoint configuration option

- CHANGELOG.md
- Makefile-package.mk
- src/nginx.go
* Adds changelog for release
* Fix the ldflag to point to the version variable
> Add changelog and ldflag for version

- .github/workflows/prerelease.yml
- .github/workflows/push_pr.yml
- build/.goreleaser.yml
- build/Dockerfile
- build/ci.mk
- build/upload_artifacts_gh.sh
- build/windows/set_exe_properties.sh
ci/migration gha multpile changes
> ci: migration gha multpile changes

- .github/workflows/prerelease.yml
- .github/workflows/push_pr.yml
- .github/workflows/release.yml
- CODE_OF_CONDUCT.md
- build/ci.mk
- tests/integration/docker-compose.yml
> core: add publish action

- .github/workflows/prerelease.yml
- .github/workflows/push_pr.yml
- Makefile
- tools/tools.go
Improve static analysis with Semgrep adding the newrelic-infra-checkers actions to get the semgrep and golangci-lint configurations.
> feat: add semgrep and infra-checkers Github Actions

- CHANGELOG.md
- build/.goreleaser.yml
- build/release.mk
> Add ARM Support and update GoReleaser

- .github/workflows/prerelease.yml
- .github/workflows/push_pr.yml
- .github/workflows/release.yml
- build/ci.mk
- build/package/windows/nri-386-installer/nri-installer.wixproj
- build/package/windows/nri-amd64-installer/nri-installer.wixproj
- build/release.mk
- build/windows/download_zip.ps1
- build/windows/extract_exe.ps1
- build/windows/package_msi.ps1
Following the PR https://github.com/newrelic/nri-postgresql/pull/135/commits/e7e437d6c4eac2d6fe50dae4d64a123477dc3060
> fix(ci/cd): fix release pipeline and adding tests

- build/windows/upload_msi.sh
Taken from https://github.com/newrelic/nri-memcached/blob/master/build/windows/upload_msi.sh
> fix(ci/cd): windows build

- nginx-config.yml.k8s_sample
Updates the k8s configuration example to match the current supported format
> chore: update k8s example
